services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: authserver-db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_EXTERNAL_PORT}
    volumes:
      - ../authserver-database/init:/docker-entrypoint-initdb.d
    networks:
      - authserver-network

networks:
  authserver-network:
    external: true